import type { AdminDataShape } from '../types';

export const initialAdminData: AdminDataShape = {
  products: [
    {
      id: 'prd-001',
      name: 'Savile Midnight Suit',
      brand: 'Imperial Sartoria',
      description: 'Italian wool suit cut for formal evenings and executive wear.',
      category: 'Suits',
      productType: 'Clothing',
      price: 620,
      discountPrice: 540,
      currency: 'USD',
      stockQuantity: 18,
      sku: 'IMP-SUIT-001',
      availability: 'In Stock',
      sizes: ['M', 'L', 'XL'],
      colors: ['Midnight Navy', 'Obsidian'],
      images: [
        'https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?auto=format&fit=crop&w=900&q=80',
      ],
      mainImageIndex: 0,
      tags: ['Best Seller', 'Featured'],
      status: 'Published',
      showOnHomepage: true,
      featured: true,
      visible: true,
      updatedAt: '2026-03-11T09:20:00Z',
    },
    {
      id: 'prd-002',
      name: 'Regent Double-Breasted Jacket',
      brand: 'Imperial Sartoria',
      description: 'Structured double-breasted jacket with horn buttons and rich texture.',
      category: 'Jackets',
      productType: 'Clothing',
      price: 410,
      discountPrice: null,
      currency: 'USD',
      stockQuantity: 9,
      sku: 'IMP-JKT-014',
      availability: 'In Stock',
      sizes: ['S', 'M', 'L'],
      colors: ['Walnut Brown'],
      images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80'],
      mainImageIndex: 0,
      tags: ['New'],
      status: 'Published',
      showOnHomepage: false,
      featured: false,
      visible: true,
      updatedAt: '2026-03-08T15:10:00Z',
    },
    {
      id: 'prd-003',
      name: 'Belgravia Silk Tie',
      brand: 'Imperial Sartoria',
      description: 'Silk jacquard tie finished with hand-rolled edges.',
      category: 'Accessories',
      productType: 'Accessory',
      price: 95,
      discountPrice: 75,
      currency: 'USD',
      stockQuantity: 31,
      sku: 'IMP-ACC-102',
      availability: 'In Stock',
      sizes: ['One Size'],
      colors: ['Champagne Gold', 'Black'],
      images: ['https://images.unsplash.com/photo-1589756823695-278bc923f962?auto=format&fit=crop&w=900&q=80'],
      mainImageIndex: 0,
      tags: ['Sale'],
      status: 'Draft',
      showOnHomepage: false,
      featured: false,
      visible: false,
      updatedAt: '2026-03-06T11:00:00Z',
    },
    {
      id: 'prd-004',
      name: 'Mayfair Cotton Shirt',
      brand: 'Imperial Sartoria',
      description: 'Crisp stretch-cotton shirt for office and evening layering.',
      category: 'Shirts',
      productType: 'Clothing',
      price: 145,
      discountPrice: null,
      currency: 'USD',
      stockQuantity: 42,
      sku: 'IMP-SHR-011',
      availability: 'In Stock',
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['White', 'Sky Blue'],
      images: ['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=900&q=80'],
      mainImageIndex: 0,
      tags: ['New'],
      status: 'Published',
      showOnHomepage: true,
      featured: true,
      visible: true,
      updatedAt: '2026-03-10T13:45:00Z',
    },
  ],
  categories: [
    {
      id: 'cat-001',
      name: 'Suits',
      image: 'https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&w=900&q=80',
      description: 'Tailored suits for formal, business, and evening wear.',
      displayOrder: 1,
      productCount: 12,
    },
    {
      id: 'cat-002',
      name: 'Jackets',
      image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=900&q=80',
      description: 'Blazers and outer layers with a sharp silhouette.',
      displayOrder: 2,
      productCount: 9,
    },
    {
      id: 'cat-003',
      name: 'Shirts',
      image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=900&q=80',
      description: 'Refined shirting for ceremony, business, and elevated casual wear.',
      displayOrder: 3,
      productCount: 16,
    },
    {
      id: 'cat-004',
      name: 'Accessories',
      image: 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=900&q=80',
      description: 'Ties, belts, and accents that complete the look.',
      displayOrder: 4,
      productCount: 7,
    },
  ],
  collections: [
    {
      id: 'col-001',
      name: 'New Arrivals',
      description: 'Latest seasonal drop for spring tailoring.',
      productIds: ['prd-001', 'prd-002', 'prd-004'],
      featured: true,
      season: 'Spring 2026',
    },
    {
      id: 'col-002',
      name: 'Formal Collection',
      description: 'Black-tie, wedding, and evening essentials.',
      productIds: ['prd-001', 'prd-003'],
      featured: false,
      season: 'Evergreen',
    },
    {
      id: 'col-003',
      name: 'Best Sellers',
      description: 'Most requested tailoring and accessories.',
      productIds: ['prd-001', 'prd-004'],
      featured: true,
      season: 'Core',
    },
  ],
  orders: [
    {
      id: 'ORD-2026-0184',
      customerId: 'cus-001',
      customerName: 'Omar Kareem',
      totalPrice: 620,
      paymentStatus: 'Paid',
      orderStatus: 'Shipped',
      createdAt: '2026-03-10T14:30:00Z',
      items: [
        {
          productId: 'prd-001',
          productName: 'Savile Midnight Suit',
          quantity: 1,
          size: 'L',
          color: 'Midnight Navy',
          price: 620,
        },
      ],
      shippingAddress: 'Baghdad, Al Mansour, 10014',
      timeline: ['Order placed', 'Payment captured', 'Packed at atelier', 'Transferred to courier'],
    },
    {
      id: 'ORD-2026-0185',
      customerId: 'cus-002',
      customerName: 'James Walker',
      totalPrice: 485,
      paymentStatus: 'Pending',
      orderStatus: 'Pending',
      createdAt: '2026-03-11T09:20:00Z',
      items: [
        {
          productId: 'prd-002',
          productName: 'Regent Double-Breasted Jacket',
          quantity: 1,
          size: 'M',
          color: 'Walnut Brown',
          price: 410,
        },
        {
          productId: 'prd-003',
          productName: 'Belgravia Silk Tie',
          quantity: 1,
          size: 'One Size',
          color: 'Champagne Gold',
          price: 75,
        },
      ],
      shippingAddress: 'London, Mayfair, W1K 7AA',
      timeline: ['Order placed', 'Awaiting payment'],
    },
    {
      id: 'ORD-2026-0186',
      customerId: 'cus-003',
      customerName: 'Mahmoud Al-Safi',
      totalPrice: 145,
      paymentStatus: 'Paid',
      orderStatus: 'Delivered',
      createdAt: '2026-03-09T18:10:00Z',
      items: [
        {
          productId: 'prd-004',
          productName: 'Mayfair Cotton Shirt',
          quantity: 1,
          size: 'M',
          color: 'White',
          price: 145,
        },
      ],
      shippingAddress: 'Erbil, Dream City, 44001',
      timeline: ['Order placed', 'Payment captured', 'Shipped', 'Delivered'],
    },
  ],
  customers: [
    {
      id: 'cus-001',
      name: 'Omar Kareem',
      email: 'omar.kareem@email.com',
      phone: '+964 770 111 2233',
      ordersCount: 4,
      totalSpent: 2440,
      joinedAt: '2025-12-18T10:00:00Z',
      segment: 'VIP',
    },
    {
      id: 'cus-002',
      name: 'James Walker',
      email: 'j.walker@email.com',
      phone: '+44 7700 900111',
      ordersCount: 2,
      totalSpent: 910,
      joinedAt: '2026-01-20T08:00:00Z',
      segment: 'Returning',
    },
    {
      id: 'cus-003',
      name: 'Mahmoud Al-Safi',
      email: 'mahmoud@email.com',
      phone: '+964 750 665 8899',
      ordersCount: 1,
      totalSpent: 540,
      joinedAt: '2026-03-09T12:00:00Z',
      segment: 'New',
    },
    {
      id: 'cus-004',
      name: 'Luca Bennett',
      email: 'luca@email.com',
      phone: '+39 333 998 7721',
      ordersCount: 5,
      totalSpent: 3180,
      joinedAt: '2025-11-02T16:00:00Z',
      segment: 'VIP',
    },
  ],
  messages: [
    {
      id: 'msg-001',
      name: 'Daniel Ross',
      email: 'daniel@agency.com',
      subject: 'Bulk corporate order',
      message: 'We need 14 formal suits for an executive event next month. Please contact us with lead time and pricing.',
      createdAt: '2026-03-11T07:15:00Z',
      read: false,
    },
    {
      id: 'msg-002',
      name: 'Ali Hassan',
      email: 'ali.hassan@email.com',
      subject: 'Alteration request',
      message: 'Can I request trouser hemming before dispatch if I place an order online?',
      createdAt: '2026-03-10T16:40:00Z',
      read: true,
    },
    {
      id: 'msg-003',
      name: 'Mason Cole',
      email: 'mason@email.com',
      subject: 'Restock request',
      message: 'Please notify me when the Savile Midnight Suit returns in XL.',
      createdAt: '2026-03-11T10:00:00Z',
      read: false,
    },
  ],
  websiteContent: {
    heroTitle: 'Timeless Elegance. Modern Tailoring.',
    heroSubtitle: 'Premium menswear crafted for confident daily wear and ceremonial moments.',
    homepageBannerTitle: 'Spring Atelier Drop',
    homepageBannerText: 'Fresh tailoring, softer palettes, and elevated accessories.',
    aboutTitle: 'Built For Men Who Dress With Intent',
    aboutText: 'Imperial Sartoria combines Italian-inspired construction with contemporary Middle Eastern refinement.',
    contactEmail: 'concierge@imperial.com',
    contactPhone: '+964 770 000 1122',
    footerLinks: ['Shop', 'About', 'Contact', 'Returns', 'Privacy'],
  },
  mediaLibrary: [
    {
      id: 'med-001',
      name: 'Hero Campaign',
      url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80',
      type: 'banner',
      uploadedAt: '2026-03-01T09:00:00Z',
    },
    {
      id: 'med-002',
      name: 'Savile Midnight Suit',
      url: 'https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?auto=format&fit=crop&w=900&q=80',
      type: 'product',
      uploadedAt: '2026-03-05T12:00:00Z',
    },
    {
      id: 'med-003',
      name: 'Gold Monogram Graphic',
      url: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=900&q=80',
      type: 'graphic',
      uploadedAt: '2026-03-08T18:00:00Z',
    },
    {
      id: 'med-004',
      name: 'Summer Collection Banner',
      url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',
      type: 'banner',
      uploadedAt: '2026-03-10T08:00:00Z',
    },
  ],
  discounts: [
    {
      id: 'dis-001',
      name: 'VIP Launch',
      code: 'VIP15',
      type: 'percentage',
      value: 15,
      expiresAt: '2026-04-15',
      active: true,
    },
    {
      id: 'dis-002',
      name: 'Tailoring Credit',
      code: 'ALTER50',
      type: 'fixed',
      value: 50,
      expiresAt: '2026-05-01',
      active: false,
    },
  ],
  settings: {
    storeName: 'Imperial Sartoria',
    logoUrl: '/imperial-logo.png',
    currency: 'USD',
    contactEmail: 'concierge@imperial.com',
    instagram: 'https://instagram.com/imperial',
    facebook: 'https://facebook.com/imperial',
    tiktok: 'https://tiktok.com/@imperial',
  },
  notifications: [
    {
      id: 'ntf-001',
      title: 'Low stock warning',
      description: 'Regent Double-Breasted Jacket is below 10 units.',
      createdAt: '2026-03-11T08:40:00Z',
      type: 'alert',
    },
    {
      id: 'ntf-002',
      title: 'New customer message',
      description: 'Daniel Ross requested a corporate order quotation.',
      createdAt: '2026-03-11T07:15:00Z',
      type: 'info',
    },
    {
      id: 'ntf-003',
      title: 'Collection published',
      description: 'New Arrivals is live on the homepage.',
      createdAt: '2026-03-10T19:00:00Z',
      type: 'success',
    },
  ],
  revenueSeries: [
    { label: 'Jan', revenue: 6400, orders: 18 },
    { label: 'Feb', revenue: 8200, orders: 26 },
    { label: 'Mar', revenue: 11380, orders: 34 },
    { label: 'Apr', revenue: 9800, orders: 31 },
    { label: 'May', revenue: 11200, orders: 36 },
    { label: 'Jun', revenue: 12500, orders: 39 },
  ],
  trafficSources: [
    { source: 'Instagram', value: 42 },
    { source: 'Direct', value: 27 },
    { source: 'Search', value: 19 },
    { source: 'Email', value: 12 },
  ],
};
